name: First Workflow

on: [push]

jobs:
  build:
    runs-on: ubutnut-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building the project..."
